Workaround / adapt to 1693751.
Addressing
  File "lib/dnf-plugins/swidtags.py", line 78, in run
    p_nevra = b"%s-%s-%s.%s" % (p["name"], p["version"], p["release"], p["arch"])
TypeError: %b requires a bytes-like object, or an object that implements __bytes__, not 'str'